version: "3"
services:
  reverseproxy:
      image: vladimirkazan/nanodegree-udacity-reverseproxy:latest
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
    image: vladimirkazan/nanodegree-udacity-restapi-user:latest
    env_file:
      ../../.env
    # environment:
    #   POSTGRESS_USERNAME: $POSTGRESS_USERNAME
    #   POSTGRESS_PASSWORD: $POSTGRESS_PASSWORD 
    #   POSTGRESS_DB: $POSTGRESS_DB 
    #   POSTGRESS_HOST: $POSTGRESS_HOST 
    #   AWS_REGION: $AWS_REGION 
    #   AWS_PROFILE: $AWS_PROFILE 
    #   AWS_BUCKET: $AWS_BUCKET
    #   JWT_SECRET: $JWT_SECRET
    #   URL: "http://localhost:8100"
  backend-feed:
    image: vladimirkazan/nanodegree-udacity-restapi-feed:latest
    volumes:
      - $HOME/.aws:/root/.aws
    env_file:
      ../../.env
    # environment:
    #   POSTGRESS_USERNAME: $POSTGRESS_USERNAME
    #   POSTGRESS_PASSWORD: $POSTGRESS_PASSWORD 
    #   POSTGRESS_DB: $POSTGRESS_DB 
    #   POSTGRESS_HOST: $POSTGRESS_HOST 
    #   AWS_REGION: $AWS_REGION 
    #   AWS_PROFILE: $AWS_PROFILE 
    #   AWS_BUCKET: $AWS_BUCKET
    #   JWT_SECRET: $JWT_SECRET
    #   URL: "http://localhost:8100"
  frontend:
    image: vladimirkazan/nanodegree-udacity-frontend:latest
    ports:
      - "8100:80"
