# k apply -k microservices/nodered/flowsudacity-c3-deployment/k8s/secrets

# https://kubectl.docs.kubernetes.io/pages/reference/kustomize.html
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: aws-secret
  files:
  - ./credentials
- name: env-secret
  env: ./.env.secret
configMapGenerator:
- name: env-config
  env: ./.env


